@CitiesApi_HostAddress = https://localhost:7025

GET {{CitiesApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{CitiesApi_HostAddress}}/api/authentication/authenticate
Authorization: Bearer {{$bearerToken}}
Content-Type: application/json

{
  //AuthenticationRequestBody
}

###

@name=string
@searchQuery=string
GET {{CitiesApi_HostAddress}}/api/v{apiVersion}/cities?name={{name}}&searchQuery={{searchQuery}}
Authorization: Bearer {{$bearerToken}}

###
